### ISSUE TITLE
Race condition causing Editor metabox field to not render

### ISSUE THREAD

**Issue by ntsim** [themosis/framework#703] opened 2019-06-27 08:50 UTC
The Editor metabox field appears to be failing to render with the TinyMCE overlay and will typically only render the underlying textarea, which is usually insufficient.

This bug seems to be be more reproducible in certain conditions:

1.  On a non-local environment e.g. production. In my local environment using Homestead, this issue doesn't seem to be reproducible.

2. Clearing the cache and reloading the page. Refreshing the page after that can actually eventually get the field to render, however this is not 100% reliable.

Consequently, I believe this is some form of race condition between the `EditorField` component rendering and TinyMCE being ready. Unfortunately, there is no errors in the console to suggest there is an actual problem though :man_shrugging:

Also, when manually initialising the textarea with TinyMCE (via devtools) with the same settings as the `EditorField` should, the editor renders correctly, so I don't think it's necessarily anything wrong with the settings or TinyMCE.

**Comment by Jaspervv** [comment] 2019-06-27 12:26
We have been encountering the same issue. Here are some of my observations:

- If it works seems to be inconsistent (often a few refreshes fixes it), because of this I think it is something timing-related in the JavaScript.  
- It always seems to work fine on Firefox.  
- The console doesn't seem to log any errors/warnings related to TinyMCE or Themosis.

## Example
We personally use the editor for an extra excerpt in our pages.

Not working example:
![not working example](https://i.imgur.com/Z3tSly5.png)

Working example:
![working example](https://i.imgur.com/T6LBQRK.png)

Code used to create the fields shown above:
```php
$postTypes = get_post_types(['public' => true]);

Metabox::make('page_info', $postTypes)
    ->setPrefix('ms_')
    ->setTitle(_x('Page info', 'metabox', WP_SOUP))
    ->setContext('side')
    ->add(Field::text('title'))
    ->add(Field::editor('excerpt'))
    ->set();
```

**Comment by ntsim** [comment] 2019-06-28 01:56
One fairly hacky way I've managed to get the editor to render more reliably is to wrap the initialisation with a `setTimeout` like:

```javascript
setTimeout(() => wp.oldEditor.initialize(this.props.field.attributes.id, settings), 500);
```
I've used 500ms here as using 100ms was still unreliable and upwards of 500ms seemed excessive.

Obviously, we really need a better way than this to initialise the editor in a 100% reliable manner however.

**Comment by jlambe** [comment] 2019-06-28 07:13
@ntsim Normally, inside the `app/Hooks/Application.php` file we load the assets (end of file). The asset is loaded at the footer and asks for dependencies to be loaded first. The old TinyMce editor is attached at some point to the global `wp` namespace on the `window` object. Perhaps by defining an additionnal dependency at asset enqueue might fix this if we can find the file responsible for the editor, not sure if there is a `media` asset name in core dependencies but that could possibly fix the issue.

**Comment by ntsim** [comment] 2019-06-30 18:13
@jlambe I did a bit of investigation and it looks like the scripts responsible for the TinyMCE editor are bought in as `wp-tinymce`.

Adding this to the `themosis_js` and `themosis_post_status` (not sure it needs to go with this one?) assets bumps the loading of the TinyMCE scripts to near the top (rather than being the last script).

Unfortunately, this doesn't seem to quite fix the issue as it still doesn't reliably render the editor. One thing that does seem to affect the rendering is having the Yoast SEO plugin installed. Deactivating this actually causes the editor to render more reliably, but obviously this isn't particularly desirable. It also doesn't seem very scalable to add the Yoast scripts as dependencies either (could potentially have to do this for any plugin that adds its own scripts).

**Comment by arjendejong12** [comment] 2019-10-16 11:53
Has there been any progress in finding the root cause of this problem? We're still occasionally  experiencing this.

**Comment by jlambe** [comment] 2022-07-07 01:05
I'm still unable to reproduce this issue. Is this still happening on a new installation (without any plugins) ? I'm going to close the issue for now, feel free to report back.

**Closed by jlambe** 2022-07-07 01:05 UTC

**Comment by arjendejong12** [comment] 2022-07-07 02:59
I'm not sure, we replaced the fields with ACF a while ago, which works perfectly.
