### ISSUE TITLE
Route generation issue?

### ISSUE THREAD

**Issue by lougreenwood** [themosis/framework#482] opened 2018-03-03 19:53 UTC
Last night a weird issue started to occur for me, after updating some CPT, I started to receive this error:

`match(): Unknown modifier '#' in /var/www/html/htdocs/admin/wp-includes/class-wp.php on line 219`

I tracked this down to the routes for Themosis pages being incorrectly generated (the following chars were appended to the routes: `#sD`, my Themosis routes would look like this: `^forms/login$#sD`).

I still have no idea how or why this started to happen, but it only affected Themosis-generated routes.

My fix is to add an additional `preg_replace` to Route::getRewriteRuleRegex() so it looks like this:

```
    public function getRewriteRuleRegex()
    {
        // Get the regex of the compiled route
        $routeRegex = $this->getCompiled()->getRegex();
        // Remove the first part (#^/) of the regex because WordPress adds this already by itself
        $routeRegex = preg_replace('/^\#\^\//', '^', $routeRegex);
        // Remove the last part (#s$) of the regex because WordPress adds this already by itself
        $routeRegex = preg_replace('/\#[s]$/', '', $routeRegex);

        // Avoid the weird "#sD" chars being appended to Themosis routes
        $routeRegex = preg_replace('/\#sD$/', '', $routeRegex);

        return $routeRegex;
    }
```

**Comment by bwrice** [comment] 2018-03-03 22:50
It has to do with the release of Laravel 5.6 . I'm guessing you ran composer install/update recently and that's when you started seeing the error.

https://github.com/themosis/themosis/issues/204

**Comment by lougreenwood** [comment] 2018-03-03 22:59
Hmmm....

I'm on Laravel 5.5.36, this is from composer.lock:

```
            "name": "illuminate/routing",
            "version": "v5.5.36",
            "source": {
                "type": "git",
                "url": "https://github.com/illuminate/routing.git",
                "reference": "badfc4a40799b89f25f83c92ffd117297899b6a2"
            },
```

However, looking at my commits, this started around the time that I upgraded 5.5.36.

**Comment by jlambe** [comment] 2018-03-05 07:36
@lougreenwood Thanks for this fix. We're still currently on version `5.5.34` of illuminate packages. We'll check how this goes on upgrading.

**Comment by CupCoffee** [comment] 2018-03-05 10:26
@jlambe Themosis requires ^5.4 which will installs 5.5.36 of the illuminate packages which will cause this issue.

**Comment by jlambe** [comment] 2018-03-05 21:35
@lougreenwood Have you tried with a fresh installation of Themosis without any installed plugins?

I've recently tested the framework with the `illuminate/routing` package version `5.6.7` combining WordPress and custom routes with and without custom route parameters. Everything is working correctly.

**Comment by lougreenwood** [comment] 2018-03-05 21:56
Good timing, I’m actually trying to setup a local env on my laptop right now - I’ll report back when it’s done.

**Comment by jlambe** [comment] 2018-03-05 22:00
@lougreenwood I've also upgraded the themosis docs site running latest illuminate/routing package (`5.6.7`). I have nothing to report for the moment. Let's keep this issue open anyway in order to get more feedback on this.

**Comment by lougreenwood** [comment] 2018-03-06 10:25
@jlambe 5.6.7 seems good to me so far, I've been able to regenerate permalinks and not get bad routes generated. However I can't use the "Rewrite Rules Inspector" plugin to fully verify. All I know is no more errors :)

However, to install 5.6.7 I had to remove a bunch of other dependencies which depend on Symphony 3, whereas Laravel 5.6 seems to require Symphony 4... (including WP CLI...), so I'm afraid that Laravel 5.6 is currently a non-solution for me :(

**Comment by jlambe** [comment] 2018-03-06 10:47
@lougreenwood Ok good to know that 5.6.7 is also working correctly on your side. I'm closing this issue then as this is related to specific project dependencies.

**Comment by lougreenwood** [comment] 2018-03-06 10:49
hmm, but that fix means that WP CLI is not compatible with Themosis.... is that really acceptable?

**Comment by lougreenwood** [comment] 2018-03-06 10:51
Seems like it's better for Themosis to lock to Laravel 5.5 until at least WP CLI supports Symphony 4 (so Laravel 5.6 is suitable).

Themosis is a WP framework after all, seems more sensible to track the WP ecosystem than the Laravel one....

I've already had to downgrade back to 5.5.36 so my system continues to work...

**Comment by lougreenwood** [comment] 2018-03-06 10:55
On further thought, maybe a better solution should be to include the additional `preg_replace()` in Route.php which I suggested above. This seems harmless if you're not affected and allows continued use of Laravel 5.5.

Ideally Laravel would just fix their stuff...

**Comment by jlambe** [comment] 2018-03-06 10:59
@lougreenwood The illuminate/routing package has served very well but in its current implementation, feels more like a hack than a fully integrated solution with the WordPress way of managing routing. I would like to dig deeper on routing for next version and provide a more reliable route helper class. Remove of the illuminate/routing package might be an option but the solution must support similar syntax and basic features.

**Comment by lougreenwood** [comment] 2018-03-06 11:06
Sure, but that doesn't help now with Laravel 5.5....

As a side note - from a user's perspective, routing feels fine to me now.
Also AFAIK, Laravel router makes use of Symfony's router, which in Symphony 4.1 is benchmarked as the fastest PHP/Regex router available - http://developer.happyr.com/symfony-route-test

So maybe best to not "throw the baby out with the bathwater" 😃

**Comment by jlambe** [comment] 2018-03-06 11:51
Nice to see indeed 😃

**Comment by lougreenwood** [comment] 2018-03-06 12:52
So... how about Laravel 5.5?

Seems you've dodged my points about why I think it should still work - mainly that explicitly dropping Laravel 5.5 in favour of Laravel 5.6 likely isn't worth dropping support for WP CLI, since this is a WP app framework and all 😉 

How's this for a deal, if you add the 1-line `preg_replace()` bandaid fix for 5.5 into a maintenance release, I'll harass Laravel with a bug report for this weird routing issue so you can later remove that `preg_replace()` bandaid from Themosis? 😄

**Comment by jlambe** [comment] 2018-03-06 13:15
😄 You can try for fun but I'm pretty sure their routing package is just fine. I'll dig into this. For now on, I won't change the framework with your fix as this does not affect all projects. I prefer redirect people to this issue until we have fully made sure routing is compatible.

**Comment by lougreenwood** [comment] 2018-03-06 13:30
To be honest I'd rather not interact with the Laravel project at all 😃, from what I've experienced, they favour useless bureaucracy over getting shit done...

I'm here if you need any help with reproducing, ping me - I'm more than happy to help...

**Comment by jlambe** [comment] 2018-03-06 13:39
Ok thanks ;)

**Comment by jlambe** [comment] 2018-03-06 13:48
@lougreenwood Well I'm definitely looking after developers to contribute on next version of the framework. If you wish to collaborate on the development or providing ideas for features, anything, ... just ping me on a new issue.

**Comment by leroy** [comment] 2018-03-07 10:06
@jlambe @lougreenwood Are you saying the issue experienced on 5.5.36 of Illuminate is no longer present in 5.6.7?

**Comment by jlambe** [comment] 2018-03-07 10:14
@leroy we currently have several applications running smoothly on version `5.5.36` of `illuminate` packages and we have tested a fresh installation with version `5.6.7` and no errors were reported. This issue is probably due to some custom code or a plugin from the project.

**Comment by leroy** [comment] 2018-03-07 10:42
@jlambe Alright, thanks for the extra insight.

I just installed the latest version of Themosis(1.3.2) with Illuminate version 5.6.8. I am able to reproduce the issue when creating a custom route as such:

`
Route::get('custom-route', function() {
    return 'test';
});
`

I then save my permalinks in Wordpress and go to /custom-route.

I get the preg_match(): Unknown modifier '#' exception.

**Comment by jlambe** [comment] 2018-03-07 10:45
@leroy Ok I'm going to test this route as well. Can you provide me your WordPress version from the `composer.lock` file? Thanks

**Comment by leroy** [comment] 2018-03-07 10:46
@jlambe 4.9.4 😄

**Comment by lougreenwood** [comment] 2018-03-07 12:26
> I then save my permalinks in Wordpress and go to /custom-route.

@leroy & @jlambe - Yes, in my testing routes *must* be re-generated for the bug to be triggered. I can use 5.5.36 fine if I don't regenerate routes through some action (in may case it was updating a CPT which initially triggered this).

Sorry if this wasn't clear enough earlier.

**Comment by leroy** [comment] 2018-03-07 12:30
@jlambe 

Excuse me for not really understanding how the routing works in themosis. I am trying to understand the workings behind the routing to find the problem.

As of now i understand that the problem occurs because symfony/routing >=3.4.5 changed something in their compiled route regex which is not compatible with Wordpress rewrite rules. However, without regenerating the rewrite rules the custom route defined in routes.php will still work.

Why are the custom routes added to the rewrite rules anyway? Is it to boost performance of custom routes?

**Comment by leroy** [comment] 2018-03-07 12:59
This is the change in symfony/routing that causes the issue:

https://github.com/symfony/routing/compare/v3.4.4...v3.4.5#diff-ee09a586c921a911a78b01fd1e11ecaaR213

**Comment by leroy** [comment] 2018-03-07 13:15
The regex compiled by Symfony gets "cleaned up" by Route::getRewriteRuleRegex to be used as a Wordpress rewrite rule.

This works in a rather static way and does not allow for Symfony to make changes in their regex. 

Based on this there are a few options in my opinion:

1. Couldn't we just use the regex Symfony supplies as the rewrite rule for Wordpress?

2. If we need to "trim" Symfony's regex why not use the part within Symfony's REGEX_DELIMITER as seen in https://github.com/symfony/routing/commit/4ac81a5c02cc73b126494f08a2e9dba05028b750#diff-ee09a586c921a911a78b01fd1e11ecaaR180.

3. Adjust Route::getRewriteRuleRegex to match the new modifier Symfony added. This is the same solution @lougreenwood offered in this issue but a tiny bit shorter.

`
public function getRewriteRuleRegex()
    {
        // Get the regex of the compiled route
        $routeRegex = $this->getCompiled()->getRegex();

        // Remove the first part (#^/) of the regex because WordPress adds this already by itself
        $routeRegex = preg_replace('/^\#\^\//', '^', $routeRegex);
        // Remove the last part (#s$) of the regex because WordPress adds this already by itself
        $routeRegex = preg_replace('/\#[sD]$/', '', $routeRegex);

        return $routeRegex;
    }
`

**Comment by jlambe** [comment] 2018-03-07 13:39
@leroy Finally I was able to reproduce the issue 😄. I don't have time right now to test this so any feedback from you or @lougreenwood or anyone on this is welcomed.

The way WordPress is handling routing is by storing rewrite rules (regexp) into the database and compare current request on any of defined rules. In order to provide custom routes, we always put them on top of defined rules array so custom rules are hit first before default WordPress ones.

Not sure the Symfony regex could work, this needs some tests but if it works, it could potentially supply the WordPress regex rules but not sure how it works regarding other plugins. I would say for now, as a fix, to implement option 3 and dig deeper on the routing for next update.

**Comment by leroy** [comment] 2018-03-07 21:09
@lougreenwood @jlambe I've been working on a PR this afternoon to rewrite the regex that removes the modifier from the Symfony regex.

Fun fact: Illuminate 5.6 actually adds another modifier 'u' to support utf-8 characters. I've adjusted the regex to remove any modifiers at all so it'll work with all future modifiers that get added.

I have had some trouble getting it to work though, Wordpress recognized the rewrite rules but then the Themosis router didn't. I will have another look at it tommorow as we at Impres heavily depend on Themosis 😄

**Comment by jlambe** [comment] 2018-03-08 06:45
@leroy Thanks a lot for taking the time to dig into this issue. I'm reopening the issue. The issue is already targeted for version `1.3.3`.

**Comment by leroy** [comment] 2018-03-08 09:56
I created a PR in https://github.com/themosis/framework/pull/485

This is my first PR ever so not really sure how to reference this issue from a PR.

No problem @jlambe, we build our websites on top of Themosis at @impres so it is time we give back to this community 👍

**Comment by leroy** [comment] 2018-03-13 08:21
Thanks @jlambe!

**Comment by jlambe** [comment] 2018-03-14 08:20
@lougreenwood You can update your project, version `1.3.3` contains a fix.

**Closed by jlambe** 2018-03-14 08:20 UTC
Labels: minor
