### ISSUE TITLE
Theme composer required packages namespace

### ISSUE THREAD

**Issue by lougreenwood** [themosis/framework#378] opened 2017-01-19 08:59 UTC
Hello,

After updating to 1.3.0, I'm now finding that any composer packages which I install using the composer.json file in my theme are not available in the root namespace for code in my theme.

e.g - something like this now fails - it was fine in 1.2.3:

`$iter = new \hanneskod\classtools\Iterator\ClassIterator( ... );`

It seems that I now need to be able to install these packages using the composer.json in the root of the Themosis project (i.e the composer file which install WordPress, Themosis etc) to be able to access these packages using the root namespace in my theme.

**Comment by jlambe** [comment] 2017-01-19 09:08
Do you mean that you have a `vendor` directory inside your theme?

Normally, if your theme has dependencies, you can define them inside the theme `composer.json` file but should not run a `composer install` from the theme. Adding dependencies there is useful when you develop your theme as have it as a package itself. Then, when you start a new project referencing your theme, its dependencies will be installed as well.

I suggest you to also define your theme dependencies into the root `composer.json` file which is the main one if you're not packaging your theme.

**Comment by lougreenwood** [comment] 2017-01-19 09:13
Yep, vendor dir in theme.

I guess I’ll need to move them to the root. I was trying to create a situation where I can re-use one Themosis installation across many projects which share variations of the same theme. The goal here would be that I share common deps in the root and theme-specific deps in the theme.

But either way - any idea why deps installed into the theme were available in the root namespace in 1.2.3 and no longer available in 1.3.0 (i.e is this a bug)?

Thanks

**Comment by jlambe** [comment] 2017-01-19 09:15
It's not a bug, old theme added a check for a theme `vendor/autoload.php` file. It has been removed as it was originally for test and not for use in production. It's bad practice to have multiple composer / vendors directories into a project.

It has been removed in new theme.

**Comment by lougreenwood** [comment] 2017-01-19 09:32
I get that generally it’s bad practice, but how we apply that rule to this use case depends on whether we view a Themosis project as one project or many. Because WP allows us to use ‘modules’ in the form of ‘themes’ and ‘plugins’, and these are interchangeable at runtime, is a Themosis project one monolithic project, or an amalgamation of many projects (in which case, we autoloading vendor deps is useful/seems to me to be a valid use)? I’d argue the latter.

If I go down the ‘Themosis and theme/plugin constitutes a single project’ route, then my use case will require me to have many many, duplicated Themosis projects, rather than one generic Themosis project and various Themosis themes/plugins to provide my per-customer customisations.

Perhaps I can add the theme check for vendor autoloading myself - can you point me to the code in 1.2.3 or similar so that I could give that a try?

Cheers

**Comment by jlambe** [comment] 2017-01-19 10:03
In fact, all you have to do, is manage your theme as a package. You can develop multiple themes on a single Themosis instance and store each theme into its own repository. Then from the root `composer.json`, you require only those themes you work on. All their dependencies will be installed automatically.

For reference, here is the old code line used: https://github.com/themosis/theme/blob/1.2.3/functions.php#L73

**Closed** 2017-01-24 10:37 UTC
