### ISSUE TITLE
Issue with infinite field when adding more than 10 items

### ISSUE THREAD

**Issue by cdarken** [themosis/framework#204] opened 2015-09-09 08:34 UTC
If you try to add more than 10 items, they only work if you save them one by one, if you add at least 2 and save, only the last one is saved.

Edit: I forgot to mention that all items above the ninth are removed, except the last.

**Comment by jlambe** [comment] 2015-09-09 09:01
Hi,

yes this issue is known and fixed on the master branch. Check the pull request #174 if you need to manually update the js file. The issue is from an error in regular expression.

**Comment by cdarken** [comment] 2015-09-09 09:12
Hi. Thanks for answering.
The problem for me is that though the settings seem to be saved correctly in the db, the saved values are not displayed.

**Comment by jlambe** [comment] 2015-09-09 09:29
Ok good to know. Let me know if you encounter any other issues.

**Closed** 2015-09-09 09:36 UTC
